const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

test("provides a pure-translation PDF export button and print stylesheet", () => {
  const root=path.join(__dirname,"..");
  const html=fs.readFileSync(path.join(root,"pdf-viewer.html"),"utf8");
  const script=fs.readFileSync(path.join(root,"pdf-viewer.js"),"utf8");
  const css=fs.readFileSync(path.join(root,"pdf-viewer.css"),"utf8");
  const content=fs.readFileSync(path.join(root,"content.js"),"utf8");
  const background=fs.readFileSync(path.join(root,"background.js"),"utf8");
  const manifest=fs.readFileSync(path.join(root,"..","manifest.json"),"utf8");
  const options=fs.readFileSync(path.join(root,"options.html"),"utf8");
  const optionsScript=fs.readFileSync(path.join(root,"options.js"),"utf8");
  const popup=fs.readFileSync(path.join(root,"popup.js"),"utf8");
  assert.match(html,/id="export-pdf"[^>]*>导出纯译文 PDF</);
  assert.match(html,/id="mark-highlight"[^>]*>标记高亮</);
  assert.match(html,/id="erase-highlight"[^>]*>擦除高亮</);
  assert.match(html,/id="auto-locate"[^>]*>联动定位：关</);
  assert.match(html,/id="clear-cache"[^>]*>清除此文献缓存</);
  assert.match(html,/id="toggle-outline"[^>]*>目录</);
  assert.match(html,/id="page-number"/);
  assert.match(html,/id="zoom-value"/);
  assert.match(html,/id="pdf-search"/);
  assert.match(html,/id="translation-task"/);
  assert.match(html,/id="app-version"/);
  assert.match(html,/id="task-errors"/);
  assert.match(html,/id="task-error-list"/);
  assert.match(html,/id="open-publisher-page"[^>]*>打开论文页完成验证</);
  assert.match(html,/id="pause-translation"[^>]*>暂停</);
  assert.match(html,/id="cancel-translation"[^>]*>取消</);
  assert.match(html,/id="retry-failed"[^>]*>重试失败部分</);
  assert.match(script,/async function exportTranslatedPdf\(\)/);
  assert.match(script,/window\.print\(\)/);
  assert.match(script,/pdfAutoLocate/);
  assert.match(script,/function scheduleCounterpartCenter\(elements\)/);
  assert.match(script,/pane\.scrollTo\(\{top:destination/);
  assert.match(script,/function resetPagePanes\(\)/);
  assert.doesNotMatch(script,/window\.scrollTo\(\{top:destination/);
  assert.match(script,/function blocksForTextSelection\(page\)[\s\S]*Math\.max\(2,page\.number\)/);
  assert.equal((script.match(/for\(const block of blocksForTextSelection\(page\)\)/g)||[]).length,2);
  assert.match(css,/@media print/);
  assert.match(css,/\.page-translation:not\(:last-child\).*break-after:page/s);
  assert.match(css,/\.reading-figure img.*max-height:205mm/s);
  assert.match(script,/detectVisualRegions\(blocks,viewport,bodyFontSize\)/);
  assert.match(script,/region\.kind==="table"/);
  assert.match(script,/if\(block\.translation\)appendLinkedSentences\(caption,page,block\)/);
  assert.match(script,/pending-figure-caption/);
  assert.match(script,/state\.pages\.push\(pageState\); drawTranslation\(pageState\)/);
  assert.match(css,/\.reading-table img.*width:100%/s);
  assert.match(css,/\.page-translation \.inline-section-heading.*font-size:13pt/s);
  assert.match(css,/mark\.user-highlight.*print-color-adjust:exact/s);
  assert.match(css,/\.mode-overlay \.translation-layer.*pointer-events:auto/s);
  assert.match(css,/\.toolbar \.auto-locate\.active/);
  assert.match(css,/\.translation-sentence\.counterpart-focus/);
  assert.match(css,/\.mode-bilingual \.pages-pane.*overflow-y:auto/s);
  assert.match(script,/document\.body\.classList\.toggle\("bilingual-active"/);
  assert.match(script,/parseReferenceList\(block\.translation,block\.text\)/);
  assert.match(css,/\.translation-reference-list li.*text-align:left/s);
  assert.match(script,/indexedDB\.open\("researchlens-reader-state",1\)/);
  assert.match(script,/async function restoreTranslationSession\(\)/);
  assert.match(script,/isLikelyUntranslated\(block\.text,match\.translation,state\.targetLanguage,\{role:block\.role\|\|""\}\)/);
  assert.match(script,/function serializeHighlights\(\)/);
  assert.match(script,/function pendingTranslationTasks\(\)/);
  assert.match(script,/async function runTranslationTasks\(tasks,isRetry\)/);
  assert.match(script,/未识别到可翻译文字/);
  assert.match(script,/async function recognizeScannedPdf\(\)/);
  assert.match(script,/type:"OCR_PDF_PAGE"/);
  assert.match(script,/本地 OCR 并精译/);
  assert.match(script,/canvas\.toDataURL\("image\/jpeg",quality\)/);
  assert.match(script,/const maximum=12\*1024\*1024/);
  assert.match(script,/roles:activeBatch\.map\(block=>block\.role/);
  assert.match(script,/const returned=Array\.isArray\(result\?\.translations\)/);
  assert.match(script,/taskState\.failed\.push\(\{page:task\.page,batch:failedBlocks,failure:/);
  assert.match(script,/code:result\?\.code/);
  assert.match(script,/stage:result\?\.stage/);
  assert.match(script,/chrome\.runtime\.getManifest\(\)\.version_name/);
  assert.match(script,/availableOverlayHeight\(block,page\.blocks,page\.figureRegions\)/);
  assert.match(script,/error\.code!=="PUBLISHER_CHALLENGE"/);
  assert.match(script,/chrome\.tabs\.create\(\{url:state\.publisherArticleUrl,active:true\}\)/);
  assert.match(script,/第 \$\{page\} 页/);
  assert.match(script,/async function waitForTranslationResume\(\)/);
  assert.match(script,/function goToPage\(number,side="both"\)/);
  assert.match(script,/function fitPageWidth\(\)/);
  assert.match(script,/function runPdfSearch\(\)/);
  assert.match(script,/function buildPdfOutline\(\)/);
  assert.match(css,/::highlight\(pdf-search-current\)/);
  assert.match(manifest,/"contextMenus"/);
  assert.match(background,/researchlens-translate-selection/);
  assert.match(content,/function showQuickTranslateTrigger\(\)/);
  assert.match(content,/typeof event\?\.key === "string"/);
  assert.match(content,/function quickTranslate\(rawText, rect\)/);
  assert.match(content,/科研译镜 · 划词翻译/);
  assert.match(background,/async function fetchTranslationApi\(endpoint, init, maxRetries = 3\)/);
  assert.match(background,/async function recognizePdfPage\(imageBase64, minimumScore = 0\.45\)/);
  assert.match(background,/retry-after/);
  assert.match(options,/id="choose-cache-directory"[^>]*>选择或更换目录</);
  assert.match(options,/id="clear-cache-directory"[^>]*>停用自定义目录</);
  assert.match(optionsScript,/chooseCacheDirectory/);
  assert.match(optionsScript,/syncInternalTranslationSessions/);
  assert.match(script,/putExternalTranslationSession\(record\)/);
  assert.match(popup,/function isLocalPdf\(value\)/);
  assert.match(popup,/chrome\.extension\.isAllowedFileSchemeAccess\(\)/);
  assert.match(background,/async function fetchLocalPdfForViewer\(source\)/);
});
