const $=id=>document.getElementById(id);const STORAGE='quantScholarMobileRecords';const CONFIG='quantScholarMobileConfig';let records=JSON.parse(localStorage.getItem(STORAGE)||'[]');let current=null;
function config(){return{backend:$('backend').value.trim().replace(/\/$/,''),token:$('token').value,sourceLang:$('sourceLang').value,domain:$('domain').value,provider:$('provider').value}}
function saveConfig(){localStorage.setItem(CONFIG,JSON.stringify(config()))}
function render(){const root=$('records');root.replaceChildren();$('count').textContent=String(records.length);for(const item of records.slice().reverse()){const card=document.createElement('article');card.className='record';const title=document.createElement('strong');title.textContent=`${item.domain} · ${item.provider} · ${new Date(item.createdAt).toLocaleString()}`;const text=document.createElement('p');text.textContent=item.translation;card.append(title,text);root.append(card)}}
function download(name,type,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function translate(){const source=$('source').value.trim(),cfg=config();if(!source)return;$('translate').disabled=true;$('status').textContent='正在根据原文、上下文与专业术语生成终稿…';saveConfig();try{if(!cfg.backend)throw new Error('请先填写电脑翻译服务地址');if(cfg.provider==='nllb'&&cfg.sourceLang==='auto')throw new Error('NLLB 不负责语言检测，请先选择原文语言');const context=records.slice(-4).map(x=>x.source).join(' ').slice(-1600);const response=await fetch(`${cfg.backend}/translate`,{method:'POST',headers:{'Content-Type':'application/json','X-QS-Token':cfg.token},body:JSON.stringify({text:source,sourceLang:cfg.sourceLang,targetLang:'zh',domain:cfg.domain,translator:cfg.provider,context,offline:cfg.provider==='nllb'})});const data=await response.json();if(!response.ok)throw new Error(data.detail||`HTTP ${response.status}`);$('translation').value=data.text||'';current={source,translation:data.text||'',domain:cfg.domain,provider:cfg.provider,createdAt:new Date().toISOString()};$('save').disabled=!current.translation;$('status').textContent=cfg.provider==='nllb'?'NLLB 离线译文已完成':'专业终稿已完成；没有引用 NLLB 预览';}catch(error){$('status').textContent=`失败：${error.message}`;}finally{$('translate').disabled=false}}
Object.assign($('backend'),{value:location.origin.startsWith('http')?location.origin:''});try{const cfg=JSON.parse(localStorage.getItem(CONFIG)||'{}');for(const key of ['backend','token','sourceLang','domain','provider'])if(cfg[key]&&$(key))$(key).value=cfg[key]}catch(_error){}
$('translate').addEventListener('click',translate);$('clear').addEventListener('click',()=>{$('source').value='';$('translation').value='';current=null;$('save').disabled=true;$('status').textContent='准备就绪'});$('save').addEventListener('click',()=>{if(!current)return;records.push(current);records=records.slice(-500);localStorage.setItem(STORAGE,JSON.stringify(records));current=null;$('save').disabled=true;render()});$('exportJson').addEventListener('click',()=>download('quant-scholar-mobile.json','application/json',JSON.stringify(records,null,2)));$('exportMarkdown').addEventListener('click',()=>download('quant-scholar-mobile.md','text/markdown',records.map(x=>`## ${x.createdAt}\n\n${x.source}\n\n${x.translation}\n`).join('\n')));render();
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('sw.js').catch(()=>{});
