// Generated by scripts/build-domain-preset.mjs. Do not edit manually.
export const QUANT_SCHOLAR_GLOSSARY_PRESET = Object.freeze([
  {
    "source": "abstract",
    "target": "摘要",
    "domain": "academic"
  },
  {
    "source": "methodology",
    "target": "研究方法",
    "domain": "academic"
  },
  {
    "source": "research question",
    "target": "研究问题",
    "domain": "academic"
  },
  {
    "source": "literature review",
    "target": "文献综述",
    "domain": "academic"
  },
  {
    "source": "hypothesis",
    "target": "研究假设",
    "domain": "academic"
  },
  {
    "source": "identification strategy",
    "target": "识别策略",
    "domain": "academic"
  },
  {
    "source": "endogeneity",
    "target": "内生性",
    "domain": "academic"
  },
  {
    "source": "instrumental variable",
    "target": "工具变量",
    "domain": "academic"
  },
  {
    "source": "robustness check",
    "target": "稳健性检验",
    "domain": "academic"
  },
  {
    "source": "sensitivity analysis",
    "target": "敏感性分析",
    "domain": "academic"
  },
  {
    "source": "replication",
    "target": "复现",
    "domain": "academic"
  },
  {
    "source": "peer review",
    "target": "同行评审",
    "domain": "academic"
  },
  {
    "source": "appendix",
    "target": "附录",
    "domain": "academic"
  },
  {
    "source": "supplementary materials",
    "target": "补充材料",
    "domain": "academic"
  },
  {
    "source": "general equilibrium",
    "target": "一般均衡",
    "domain": "economics"
  },
  {
    "source": "partial equilibrium",
    "target": "局部均衡",
    "domain": "economics"
  },
  {
    "source": "marginal utility",
    "target": "边际效用",
    "domain": "economics"
  },
  {
    "source": "price elasticity",
    "target": "价格弹性",
    "domain": "economics"
  },
  {
    "source": "consumer surplus",
    "target": "消费者剩余",
    "domain": "economics"
  },
  {
    "source": "producer surplus",
    "target": "生产者剩余",
    "domain": "economics"
  },
  {
    "source": "deadweight loss",
    "target": "无谓损失",
    "domain": "economics"
  },
  {
    "source": "opportunity cost",
    "target": "机会成本",
    "domain": "economics"
  },
  {
    "source": "comparative advantage",
    "target": "比较优势",
    "domain": "economics"
  },
  {
    "source": "monetary policy",
    "target": "货币政策",
    "domain": "economics"
  },
  {
    "source": "fiscal policy",
    "target": "财政政策",
    "domain": "economics"
  },
  {
    "source": "output gap",
    "target": "产出缺口",
    "domain": "economics"
  },
  {
    "source": "natural rate of unemployment",
    "target": "自然失业率",
    "domain": "economics"
  },
  {
    "source": "Phillips curve",
    "target": "菲利普斯曲线",
    "domain": "economics"
  },
  {
    "source": "purchasing power parity",
    "target": "购买力平价",
    "domain": "economics"
  },
  {
    "source": "difference in differences",
    "target": "双重差分法",
    "domain": "economics"
  },
  {
    "source": "regression discontinuity",
    "target": "断点回归",
    "domain": "economics"
  },
  {
    "source": "fixed effects",
    "target": "固定效应",
    "domain": "economics"
  },
  {
    "source": "random effects",
    "target": "随机效应",
    "domain": "economics"
  },
  {
    "source": "expected return",
    "target": "期望收益率",
    "domain": "finance"
  },
  {
    "source": "realized return",
    "target": "已实现收益率",
    "domain": "finance"
  },
  {
    "source": "excess return",
    "target": "超额收益率",
    "domain": "finance"
  },
  {
    "source": "risk premium",
    "target": "风险溢价",
    "domain": "finance"
  },
  {
    "source": "yield to maturity",
    "target": "到期收益率",
    "domain": "finance"
  },
  {
    "source": "duration",
    "target": "久期",
    "domain": "finance"
  },
  {
    "source": "modified duration",
    "target": "修正久期",
    "domain": "finance"
  },
  {
    "source": "convexity",
    "target": "凸性",
    "domain": "finance"
  },
  {
    "source": "term structure",
    "target": "期限结构",
    "domain": "finance"
  },
  {
    "source": "credit spread",
    "target": "信用利差",
    "domain": "finance"
  },
  {
    "source": "free cash flow",
    "target": "自由现金流",
    "domain": "finance"
  },
  {
    "source": "weighted average cost of capital",
    "target": "加权平均资本成本",
    "domain": "finance"
  },
  {
    "source": "discounted cash flow",
    "target": "现金流折现法",
    "domain": "finance"
  },
  {
    "source": "enterprise value",
    "target": "企业价值",
    "domain": "finance"
  },
  {
    "source": "equity value",
    "target": "股权价值",
    "domain": "finance"
  },
  {
    "source": "book-to-market ratio",
    "target": "账面市值比",
    "domain": "finance"
  },
  {
    "source": "earnings yield",
    "target": "盈利收益率",
    "domain": "finance"
  },
  {
    "source": "financial leverage",
    "target": "财务杠杆",
    "domain": "finance"
  },
  {
    "source": "working capital",
    "target": "营运资本",
    "domain": "finance"
  },
  {
    "source": "liquidity premium",
    "target": "流动性溢价",
    "domain": "finance"
  },
  {
    "source": "eigenvalue",
    "target": "特征值",
    "domain": "mathematics"
  },
  {
    "source": "eigenvector",
    "target": "特征向量",
    "domain": "mathematics"
  },
  {
    "source": "singular value decomposition",
    "target": "奇异值分解",
    "domain": "mathematics"
  },
  {
    "source": "positive semidefinite",
    "target": "半正定",
    "domain": "mathematics"
  },
  {
    "source": "orthogonal projection",
    "target": "正交投影",
    "domain": "mathematics"
  },
  {
    "source": "convex optimization",
    "target": "凸优化",
    "domain": "mathematics"
  },
  {
    "source": "Lagrange multiplier",
    "target": "拉格朗日乘子",
    "domain": "mathematics"
  },
  {
    "source": "Karush-Kuhn-Tucker conditions",
    "target": "KKT 条件",
    "domain": "mathematics"
  },
  {
    "source": "necessary condition",
    "target": "必要条件",
    "domain": "mathematics"
  },
  {
    "source": "sufficient condition",
    "target": "充分条件",
    "domain": "mathematics"
  },
  {
    "source": "partial derivative",
    "target": "偏导数",
    "domain": "mathematics"
  },
  {
    "source": "gradient",
    "target": "梯度",
    "domain": "mathematics"
  },
  {
    "source": "Hessian matrix",
    "target": "海森矩阵",
    "domain": "mathematics"
  },
  {
    "source": "Lebesgue integral",
    "target": "勒贝格积分",
    "domain": "mathematics"
  },
  {
    "source": "measurable function",
    "target": "可测函数",
    "domain": "mathematics"
  },
  {
    "source": "almost surely",
    "target": "几乎必然",
    "domain": "mathematics"
  },
  {
    "source": "stochastic process",
    "target": "随机过程",
    "domain": "mathematics"
  },
  {
    "source": "martingale",
    "target": "鞅",
    "domain": "mathematics"
  },
  {
    "source": "Brownian motion",
    "target": "布朗运动",
    "domain": "mathematics"
  },
  {
    "source": "Itô's lemma",
    "target": "伊藤引理",
    "domain": "mathematics"
  },
  {
    "source": "return value",
    "target": "返回值",
    "domain": "programming"
  },
  {
    "source": "class",
    "target": "类",
    "domain": "programming"
  },
  {
    "source": "race condition",
    "target": "竞态条件",
    "domain": "programming"
  },
  {
    "source": "deadlock",
    "target": "死锁",
    "domain": "programming"
  },
  {
    "source": "thread safety",
    "target": "线程安全",
    "domain": "programming"
  },
  {
    "source": "dependency injection",
    "target": "依赖注入",
    "domain": "programming"
  },
  {
    "source": "runtime",
    "target": "运行时",
    "domain": "programming"
  },
  {
    "source": "compile time",
    "target": "编译期",
    "domain": "programming"
  },
  {
    "source": "garbage collection",
    "target": "垃圾回收",
    "domain": "programming"
  },
  {
    "source": "memory leak",
    "target": "内存泄漏",
    "domain": "programming"
  },
  {
    "source": "stack trace",
    "target": "堆栈跟踪",
    "domain": "programming"
  },
  {
    "source": "exception handling",
    "target": "异常处理",
    "domain": "programming"
  },
  {
    "source": "asynchronous programming",
    "target": "异步编程",
    "domain": "programming"
  },
  {
    "source": "event loop",
    "target": "事件循环",
    "domain": "programming"
  },
  {
    "source": "time complexity",
    "target": "时间复杂度",
    "domain": "programming"
  },
  {
    "source": "space complexity",
    "target": "空间复杂度",
    "domain": "programming"
  },
  {
    "source": "binary search tree",
    "target": "二叉搜索树",
    "domain": "programming"
  },
  {
    "source": "application programming interface",
    "target": "应用程序编程接口",
    "domain": "programming"
  },
  {
    "source": "continuous integration",
    "target": "持续集成",
    "domain": "programming"
  },
  {
    "source": "version control",
    "target": "版本控制",
    "domain": "programming"
  },
  {
    "source": "factor exposure",
    "target": "因子暴露",
    "domain": "quant_finance"
  },
  {
    "source": "factor loading",
    "target": "因子载荷",
    "domain": "quant_finance"
  },
  {
    "source": "alpha",
    "target": "阿尔法",
    "domain": "quant_finance"
  },
  {
    "source": "beta",
    "target": "贝塔",
    "domain": "quant_finance"
  },
  {
    "source": "tracking error",
    "target": "跟踪误差",
    "domain": "quant_finance"
  },
  {
    "source": "information ratio",
    "target": "信息比率",
    "domain": "quant_finance"
  },
  {
    "source": "Sharpe ratio",
    "target": "夏普比率",
    "domain": "quant_finance"
  },
  {
    "source": "Sortino ratio",
    "target": "索提诺比率",
    "domain": "quant_finance"
  },
  {
    "source": "maximum drawdown",
    "target": "最大回撤",
    "domain": "quant_finance"
  },
  {
    "source": "value at risk",
    "target": "风险价值",
    "domain": "quant_finance"
  },
  {
    "source": "expected shortfall",
    "target": "预期损失",
    "domain": "quant_finance"
  },
  {
    "source": "backtest",
    "target": "回测",
    "domain": "quant_finance"
  },
  {
    "source": "look-ahead bias",
    "target": "前视偏差",
    "domain": "quant_finance"
  },
  {
    "source": "survivorship bias",
    "target": "幸存者偏差",
    "domain": "quant_finance"
  },
  {
    "source": "data snooping",
    "target": "数据窥探",
    "domain": "quant_finance"
  },
  {
    "source": "overfitting",
    "target": "过拟合",
    "domain": "quant_finance"
  },
  {
    "source": "turnover",
    "target": "换手率",
    "domain": "quant_finance"
  },
  {
    "source": "slippage",
    "target": "滑点",
    "domain": "quant_finance"
  },
  {
    "source": "transaction cost",
    "target": "交易成本",
    "domain": "quant_finance"
  },
  {
    "source": "market neutral",
    "target": "市场中性",
    "domain": "quant_finance"
  },
  {
    "source": "dollar neutral",
    "target": "资金中性",
    "domain": "quant_finance"
  },
  {
    "source": "rebalancing",
    "target": "再平衡",
    "domain": "quant_finance"
  },
  {
    "source": "out-of-sample",
    "target": "样本外",
    "domain": "quant_finance"
  },
  {
    "source": "walk-forward analysis",
    "target": "滚动前向分析",
    "domain": "quant_finance"
  },
  {
    "source": "statistical power",
    "target": "统计功效",
    "domain": "statistics"
  },
  {
    "source": "null hypothesis",
    "target": "原假设",
    "domain": "statistics"
  },
  {
    "source": "alternative hypothesis",
    "target": "备择假设",
    "domain": "statistics"
  },
  {
    "source": "p-value",
    "target": "p 值",
    "domain": "statistics"
  },
  {
    "source": "type I error",
    "target": "第一类错误",
    "domain": "statistics"
  },
  {
    "source": "type II error",
    "target": "第二类错误",
    "domain": "statistics"
  },
  {
    "source": "unbiased estimator",
    "target": "无偏估计量",
    "domain": "statistics"
  },
  {
    "source": "consistent estimator",
    "target": "一致估计量",
    "domain": "statistics"
  },
  {
    "source": "confidence interval",
    "target": "置信区间",
    "domain": "statistics"
  },
  {
    "source": "maximum likelihood estimation",
    "target": "最大似然估计",
    "domain": "statistics"
  },
  {
    "source": "ordinary least squares",
    "target": "普通最小二乘法",
    "domain": "statistics"
  },
  {
    "source": "heteroskedasticity",
    "target": "异方差性",
    "domain": "statistics"
  },
  {
    "source": "multicollinearity",
    "target": "多重共线性",
    "domain": "statistics"
  },
  {
    "source": "autocorrelation",
    "target": "自相关",
    "domain": "statistics"
  },
  {
    "source": "stationary process",
    "target": "平稳过程",
    "domain": "statistics"
  },
  {
    "source": "unit root",
    "target": "单位根",
    "domain": "statistics"
  },
  {
    "source": "cointegration",
    "target": "协整",
    "domain": "statistics"
  },
  {
    "source": "central limit theorem",
    "target": "中心极限定理",
    "domain": "statistics"
  },
  {
    "source": "law of large numbers",
    "target": "大数定律",
    "domain": "statistics"
  },
  {
    "source": "Bayesian posterior",
    "target": "贝叶斯后验分布",
    "domain": "statistics"
  }
].map(Object.freeze));
