// Kami Subs — background service worker
// Coordinates: popup <-> offscreen (audio capture) <-> content (overlay)
//             popup -> native host (spawns the Python backend)

import { mergeCaptionSource, shouldCommitCaption } from './caption-buffer.js';

const OFFSCREEN_DOC = 'offscreen.html';
const NATIVE_HOST   = 'com.quant_scholar.translator';

let activeTabId = null;
let isCapturing = false;
let wsState = 'idle';           // idle | connecting | connected | error | closed
let backendState = 'unknown';   // unknown | starting | up | down | unavailable
let backendInfo = {};           // { pid?, wsUrl?, lastError? }
let nativePort = null;          // chrome.runtime.Port to native host, or null
let captureSession = null;
let captureMode = 'idle';       // idle | native-captions | audio-asr
let activeSettings = {};
let captionQueue = Promise.resolve();
let nativePending = null;
let nativeCommitTimer = null;

chrome.storage.local.get(['isCapturing', 'activeTabId', 'currentLearningSession', 'settings']).then(stored => {
  isCapturing = Boolean(stored.isCapturing);
  activeTabId = stored.activeTabId ?? null;
  captureSession = stored.currentLearningSession || null;
  captureMode = captureSession?.captureMode || (isCapturing ? 'audio-asr' : 'idle');
  activeSettings = stored.settings || {};
});

function isoNow() { return new Date().toISOString(); }

function formatMediaTime(seconds) {
  if (!Number.isFinite(seconds)) return null;
  const whole = Math.max(0, Math.floor(seconds));
  const h = Math.floor(whole / 3600);
  const m = Math.floor((whole % 3600) / 60);
  const s = whole % 60;
  return h ? `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}` : `${m}:${String(s).padStart(2, '0')}`;
}

async function currentMediaTime() {
  if (activeTabId == null) return null;
  try {
    const response = await chrome.tabs.sendMessage(activeTabId, { type: 'media:time' });
    return Number.isFinite(response?.mediaTime) ? response.mediaTime : null;
  } catch (_error) {
    return null;
  }
}

async function persistFinalSegment(msg) {
  if (!captureSession || !msg.isFinal || !(msg.raw || msg.text)) return;
  if (msg.stage === 'source' || String(msg.stage || '').includes('preview')) return;
  const source = String(msg.raw || '').trim();
  const translation = String(msg.text || '').trim();
  const resolvedMediaTime = Number.isFinite(msg.mediaTime) ? msg.mediaTime : await currentMediaTime();
  const previous = captureSession.segments.at(-1);
  if (previous && previous.source.toLocaleLowerCase() === source.toLocaleLowerCase()
      && (resolvedMediaTime == null || previous.mediaTime == null || Math.abs(previous.mediaTime - resolvedMediaTime) < 3)) {
    return;
  }
  const segment = {
    id: `${captureSession.id}:${captureSession.segments.length + 1}`,
    capturedAt: isoNow(),
    sourceLanguage: msg.detectedLang || captureSession.sourceLanguage || 'auto',
    source,
    translation,
    domain: captureSession.domain,
    mediaTime: resolvedMediaTime,
    provider: msg.provider || captureMode,
    stage: msg.stage || 'final'
  };
  if (!segment.source && !segment.translation) return;
  captureSession.segments.push(segment);
  captureSession.updatedAt = segment.capturedAt;
  await chrome.storage.local.set({ currentLearningSession: captureSession });
}

function sessionMarkdown(session) {
  const lines = [
    '---',
    `title: ${JSON.stringify(session.title || 'Untitled learning session')}`,
    `source_url: ${JSON.stringify(session.url || '')}`,
    `domain: ${session.domain || 'auto'}`,
    `captured_at: ${session.startedAt}`,
    'content_type: video_transcript',
    '---', '',
    `# ${session.title || 'Learning session'}`, '',
    '> Generated by Quant Scholar Translator. Review terminology and numerical claims against the source.', ''
  ];
  for (const item of session.segments || []) {
    const time = formatMediaTime(item.mediaTime);
    lines.push(`## ${time ? `[${time}] ` : ''}${item.capturedAt}`, '', item.source || '', '', item.translation || '', '');
  }
  return lines.join('\n');
}

function srtTimestamp(seconds) {
  const ms = Math.max(0, Math.round(seconds * 1000));
  const h = Math.floor(ms / 3600000);
  const m = Math.floor((ms % 3600000) / 60000);
  const s = Math.floor((ms % 60000) / 1000);
  const rest = ms % 1000;
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')},${String(rest).padStart(3, '0')}`;
}

function sessionSrt(session) {
  const started = Date.parse(session.startedAt);
  return (session.segments || []).map((item, index, all) => {
    const wallTime = Math.max(0, (Date.parse(item.capturedAt) - started) / 1000);
    const start = Number.isFinite(item.mediaTime) ? item.mediaTime : wallTime;
    const next = all[index + 1];
    const nextStart = Number.isFinite(next?.mediaTime) ? next.mediaTime : null;
    const end = nextStart != null && nextStart > start ? Math.max(start + 0.8, nextStart - 0.05) : start + 4;
    const bilingual = [item.source, item.translation].filter(Boolean).join('\n');
    return `${index + 1}\n${srtTimestamp(start)} --> ${srtTimestamp(end)}\n${bilingual}\n`;
  }).join('\n');
}

async function exportCurrentSession(format = 'markdown') {
  const stored = await chrome.storage.local.get('currentLearningSession');
  const session = stored.currentLearningSession;
  if (!session || !session.segments?.length) throw new Error('No finalized transcript to export');
  const safe = (session.title || 'learning-session').replace(/[\\/:*?"<>|]+/g, '-').slice(0, 80);
  const json = format === 'json';
  const srt = format === 'srt';
  const body = json ? JSON.stringify(session, null, 2) : (srt ? sessionSrt(session) : sessionMarkdown(session));
  const mime = json ? 'application/json' : (srt ? 'application/x-subrip' : 'text/markdown');
  const ext = json ? 'json' : (srt ? 'srt' : 'md');
  const url = `data:${mime};charset=utf-8,${encodeURIComponent(body)}`;
  return chrome.downloads.download({ url, filename: `quant-scholar/${safe}.${ext}`, saveAs: true });
}

async function hasOffscreenDocument() {
  if (chrome.runtime.getContexts) {
    const contexts = await chrome.runtime.getContexts({
      contextTypes: ['OFFSCREEN_DOCUMENT'],
      documentUrls: [chrome.runtime.getURL(OFFSCREEN_DOC)]
    });
    return contexts.length > 0;
  }
  return false;
}

async function ensureOffscreen() {
  if (await hasOffscreenDocument()) return;
  await chrome.offscreen.createDocument({
    url: OFFSCREEN_DOC,
    reasons: ['USER_MEDIA'],
    justification: 'Capture tab audio for live subtitle generation'
  });
}

async function ensureContentScript(tabId) {
  // First try to ping the content script.
  try {
    await chrome.tabs.sendMessage(tabId, { type: 'ping' });
    return; // already there
  } catch (e) {
    // Not loaded — inject programmatically. Required for tabs opened before
    // the extension was installed/reloaded.
  }
  try {
    await chrome.scripting.insertCSS({
      target: { tabId },
      files: ['content.css']
    });
  } catch (e) { /* ignore — may already be injected */ }
  await chrome.scripting.executeScript({
    target: { tabId },
    files: ['content.js']
  });
}

// ---- Native Messaging: spawn the Python backend on demand ------------------
//
// Graceful degradation: if the user hasn't installed the native host, every
// Start still works as long as they launched the backend manually. The host
// is a nice-to-have, not a hard dependency.

function connectNative() {
  // chrome.runtime.connectNative is synchronous — failure shows up on the
  // onDisconnect listener with chrome.runtime.lastError set.
  try {
    nativePort = chrome.runtime.connectNative(NATIVE_HOST);
  } catch (e) {
    backendState = 'unavailable';
    backendInfo = { lastError: String(e) };
    nativePort = null;
    return false;
  }

  nativePort.onMessage.addListener((msg) => {
    switch (msg.type) {
      case 'started':
        backendState = 'up';
        backendInfo = { pid: msg.pid, wsUrl: msg.wsUrl };
        break;
      case 'already_up':
        backendState = 'up';
        backendInfo = { wsUrl: msg.wsUrl, note: 'attached to existing backend' };
        break;
      case 'stopped':
        backendState = 'down';
        backendInfo = {};
        break;
      case 'status':
        backendState = msg.running ? 'up' : 'down';
        backendInfo = { pid: msg.pid || null, wsUrl: msg.wsUrl };
        break;
      case 'error':
        backendState = 'down';
        backendInfo = { lastError: msg.message };
        console.error('[kami-subs native]', msg.message);
        break;
      case 'log':
        // Backend stdout/stderr, surfaced for debugging. Comment out if noisy.
        console.log('[kami-backend]', msg.line);
        break;
    }
  });

  nativePort.onDisconnect.addListener(() => {
    const err = chrome.runtime.lastError;
    if (err) {
      // Most common: "Specified native messaging host not found." — the user
      // hasn't run install.ps1 yet. Mark unavailable so we stop trying.
      backendState = 'unavailable';
      backendInfo = { lastError: err.message || String(err) };
      console.warn('[kami-subs] native host unavailable:', err.message);
    } else if (backendState !== 'down') {
      backendState = 'down';
    }
    nativePort = null;
  });

  return true;
}

async function ensureBackend(settings) {
  // Already attempted and unavailable — don't keep retrying; user will start
  // the backend manually or run install.ps1.
  if (backendState === 'unavailable') return false;
  if (backendState === 'up' && nativePort) return true;

  if (!nativePort) {
    if (!connectNative()) return false;
  }

  // Pull whisper settings off the popup settings object if present.
  const startMsg = {
    type: 'start',
    model:      settings.model      || undefined,
    device:     settings.device     || undefined,
    compute:    settings.compute    || undefined,
    translator: settings.translator || undefined,
  };
  backendState = 'starting';
  try {
    nativePort.postMessage(startMsg);
  } catch (e) {
    backendState = 'unavailable';
    backendInfo = { lastError: String(e) };
    nativePort = null;
    return false;
  }

  // Block startCapture until the backend confirms ready (or errors out).
  // The launcher.py only sends 'started' after the port is actually accepting
  // connections, so 'up' = WS will succeed. Without this wait, the offscreen
  // WS open call races whisper model load (1-4s warm, 10s+ cold large-v3).
  // 60s ceiling matches launcher's deadline.
  await new Promise((resolve) => {
    const t0 = Date.now();
    const tick = setInterval(() => {
      if (backendState === 'up' || backendState === 'unavailable' || Date.now() - t0 > 60000) {
        clearInterval(tick);
        resolve();
      }
    }, 150);
  });
  return backendState !== 'unavailable';
}

function stopBackend() {
  if (!nativePort) return;
  try { nativePort.postMessage({ type: 'stop' }); } catch (e) { /* ignore */ }
  try { nativePort.disconnect(); } catch (e) { /* ignore */ }
  nativePort = null;
  backendState = 'down';
}

// The toolbar icon opens the page-level floating workspace. Chrome's own
// action popup is intentionally disabled so its browser-controlled anchor can
// never compete with the draggable menu.
chrome.action.onClicked.addListener(async tab => {
  if (!tab?.id) return;
  try {
    await ensureContentScript(tab.id);
    await chrome.tabs.sendMessage(tab.id, { type: 'floating:toggle-menu' });
  } catch (_error) {
    await chrome.tabs.create({ url: chrome.runtime.getURL('popup/popup.html') });
  }
});

function translationHttpUrl(settings) {
  const wsUrl = settings.backendUrl || 'ws://127.0.0.1:8765/ws';
  const url = new URL(wsUrl.replace(/^ws:/, 'http:').replace(/^wss:/, 'https:'));
  url.pathname = '/translate';
  url.search = '';
  return url.toString();
}

function normalizedTranslationMode(settings = activeSettings) {
  return ['professional', 'quick', 'offline'].includes(settings?.translationMode)
    ? settings.translationMode
    : 'professional';
}

function professionalTranslator(settings = activeSettings) {
  return ['codex', 'kimi_subscription', 'llm'].includes(settings?.translator)
    ? settings.translator
    : 'kimi_subscription';
}

function recentSourceContext() {
  return (captureSession?.segments || []).slice(-4).map(item => item.source).filter(Boolean).join(' ').slice(-1600);
}

async function translateNativeCaption(msg, translator, offline = false) {
  const response = await fetch(translationHttpUrl(activeSettings), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      text: msg.source,
      sourceLang: msg.sourceLang || activeSettings.sourceLang || 'auto',
      targetLang: activeSettings.targetLang || 'zh',
      domain: activeSettings.domain || 'auto',
      translator,
      context: recentSourceContext(),
      offline
    })
  });
  if (!response.ok) throw new Error(`Translation service returned HTTP ${response.status}`);
  const result = await response.json();
  if (!String(result.text || '').trim()) throw new Error('Translation service returned an empty final result');
  return result.text;
}

async function processNativeCaption(msg, sessionId) {
  const stillCurrent = () => isCapturing && captureMode === 'native-captions' && captureSession?.id === sessionId;
  if (!stillCurrent() || !msg.source) return;
  const mode = normalizedTranslationMode();
  const finalProvider = mode === 'offline' ? 'nllb' : professionalTranslator();
  if (mode === 'quick') {
    try {
      const preview = await translateNativeCaption(msg, 'nllb', true);
      if (stillCurrent() && activeTabId != null) {
        await chrome.tabs.sendMessage(activeTabId, {
          type: 'overlay:text', text: preview, raw: msg.source, isFinal: false,
          stage: 'quick-preview', provider: 'nllb'
        });
      }
    } catch (error) {
      console.info('[quant-scholar] local preview skipped:', error);
    }
  }

  if (!stillCurrent()) return;
  let text;
  try {
    text = await translateNativeCaption(msg, finalProvider, mode === 'offline');
  } catch (error) {
    console.warn('[quant-scholar] final caption translation unavailable:', error);
    if (stillCurrent() && activeTabId != null) {
      await chrome.tabs.sendMessage(activeTabId, {
        type: 'overlay:error',
        message: mode === 'offline' ? '本地 NLLB 暂不可用' : '专业翻译暂不可用，未写入知识库'
      });
    }
    return;
  }
  if (!stillCurrent()) return;
  const transcript = {
    text,
    raw: msg.source,
    detectedLang: msg.sourceLang || 'auto',
    mediaTime: msg.mediaTime,
    provider: finalProvider,
    stage: mode === 'offline' ? 'offline-final' : 'professional-final',
    isFinal: true
  };
  await persistFinalSegment(transcript);
  if (activeTabId != null) {
    await chrome.tabs.sendMessage(activeTabId, {
      type: 'overlay:text', text, raw: msg.source, isFinal: true,
      stage: transcript.stage, provider: finalProvider
    });
  }
}

function clearNativePending() {
  if (nativeCommitTimer) clearTimeout(nativeCommitTimer);
  nativeCommitTimer = null;
  nativePending = null;
}

function flushNativePending() {
  if (!nativePending) return;
  const pending = nativePending;
  clearNativePending();
  captionQueue = captionQueue.catch(() => undefined).then(() => processNativeCaption(pending, pending.sessionId));
}

async function bufferNativeCaption(msg) {
  if (!isCapturing || captureMode !== 'native-captions' || !captureSession || !msg.source) return;
  const now = Date.now();
  if (!nativePending) nativePending = { ...msg, source: '', startedAt: now, sessionId: captureSession.id };
  nativePending.source = mergeCaptionSource(nativePending.source, msg.source);
  const pending = nativePending;
  const display = chrome.tabs.sendMessage(activeTabId, {
    type: 'overlay:text', text: '', raw: nativePending.source, isFinal: false,
    stage: 'source', provider: professionalTranslator()
  }).catch(() => {});
  if (shouldCommitCaption(pending.source, now - pending.startedAt)) {
    flushNativePending();
  } else {
    if (nativeCommitTimer) clearTimeout(nativeCommitTimer);
    nativeCommitTimer = setTimeout(flushNativePending, 2200);
  }
  await display;
}

async function initializeSession(tabId, settings) {
  clearNativePending();
  const tab = await chrome.tabs.get(tabId);
  activeTabId = tabId;
  activeSettings = settings;
  captureSession = {
    schemaVersion: 1,
    id: `session-${Date.now()}`,
    title: tab.title || 'Web video',
    url: tab.url || '',
    startedAt: isoNow(),
    updatedAt: isoNow(),
    sourceLanguage: settings.sourceLang || 'auto',
    targetLanguage: settings.targetLang || 'zh',
    domain: settings.domain || 'auto',
    translationMode: normalizedTranslationMode(settings),
    professionalTranslator: professionalTranslator(settings),
    captureMode: 'detecting',
    segments: []
  };
  await chrome.storage.local.set({ currentLearningSession: captureSession });
}

async function startCapture(tabId, settings) {
  // Best-effort: try to spawn the backend before we start capturing. If the
  // native host isn't installed, fall through — user may have launched it
  // manually, in which case the WS connect still works.
  // Make sure the overlay is mounted before we start sending transcripts.
  try {
    await ensureContentScript(tabId);
  } catch (e) {
    console.warn('[kami-subs] could not inject content script (restricted page?):', e);
  }

  await initializeSession(tabId, settings);
  try {
    await chrome.tabs.sendMessage(tabId, { type: 'overlay:mount', settings });
  } catch (_error) { /* restricted page */ }

  await ensureBackend(settings);

  // Any player exposing HTML5 TextTracks or a readable caption surface gets
  // the more accurate source-caption path. Every other site falls back to
  // capturing the tab audio, so site-specific support is never required.
  if (settings.preferNativeCaptions !== false) {
    try {
      isCapturing = true;
      captureMode = 'native-captions';
      const probe = await chrome.tabs.sendMessage(tabId, { type: 'captions:start', settings });
      if (probe?.ok) {
        captureSession.captureMode = 'native-captions';
        captureSession.captionProvider = probe.provider;
        wsState = 'connected';
        await chrome.storage.local.set({ isCapturing: true, activeTabId: tabId, currentLearningSession: captureSession });
        return;
      }
      isCapturing = false;
      captureMode = 'idle';
    } catch (_error) { /* no readable caption surface */ }
  }

  await ensureOffscreen();

  const streamId = await new Promise((resolve, reject) => {
    chrome.tabCapture.getMediaStreamId({ targetTabId: tabId }, (id) => {
      if (chrome.runtime.lastError) return reject(chrome.runtime.lastError);
      resolve(id);
    });
  });

  await chrome.runtime.sendMessage({
    target: 'offscreen',
    type: 'start',
    streamId,
    settings
  });

  captureMode = 'audio-asr';
  captureSession.captureMode = captureMode;
  isCapturing = true;
  wsState = 'connecting';
  await chrome.storage.local.set({ isCapturing: true, activeTabId: tabId });

  await chrome.storage.local.set({ currentLearningSession: captureSession });
}

async function stopCapture() {
  clearNativePending();
  if (await hasOffscreenDocument()) {
    await chrome.runtime.sendMessage({ target: 'offscreen', type: 'stop' });
  }
  if (activeTabId != null) {
    try {
      await chrome.tabs.sendMessage(activeTabId, { type: 'captions:stop' });
      await chrome.tabs.sendMessage(activeTabId, { type: 'overlay:unmount' });
    } catch (e) { /* tab may be gone */ }
  }
  // Tear down the backend too — Stop should fully clean up, not leave the
  // Python process running silently. If the user prefers always-on, they can
  // launch the Quant Scholar service manually and attach on the next Start.
  stopBackend();
  isCapturing = false;
  captureMode = 'idle';
  activeSettings = {};
  wsState = 'idle';
  await chrome.storage.local.set({ isCapturing: false, activeTabId: null });
  activeTabId = null;
}

chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  (async () => {
    try {
      if (msg.target && msg.target !== 'background') return;

      switch (msg.type) {
        case 'capture:start': {
          const tab = msg.tabId
            ? await chrome.tabs.get(msg.tabId)
            : (sender.tab || (await chrome.tabs.query({ active: true, currentWindow: true }))[0]);
          try {
            await startCapture(tab.id, msg.settings || {});
          } catch (error) {
            await stopCapture();
            throw error;
          }
          sendResponse({ ok: true });
          break;
        }
        case 'capture:stop': {
          await stopCapture();
          sendResponse({ ok: true });
          break;
        }
        case 'capture:status': {
          sendResponse({ isCapturing, activeTabId, captureMode, wsState, backendState, backendInfo });
          break;
        }
        case 'ws:state': {
          wsState = msg.state;
          break;
        }
        case 'transcript': {
          await persistFinalSegment(msg);
          // Forward transcript from offscreen -> content script overlay
          if (activeTabId != null) {
            try {
              await chrome.tabs.sendMessage(activeTabId, {
                type: 'overlay:text',
                text: msg.text,
                raw: msg.raw,
                isFinal: msg.isFinal,
                stage: msg.stage,
                provider: msg.provider
              });
            } catch (e) { /* ignore */ }
          }
          break;
        }
        case 'caption:segment': {
          if (sender.tab?.id === activeTabId) await bufferNativeCaption(msg);
          sendResponse({ ok: true });
          break;
        }
        case 'knowledge:export': {
          const downloadId = await exportCurrentSession(msg.format || 'markdown');
          sendResponse({ ok: true, downloadId });
          break;
        }
        case 'knowledge:clear': {
          captureSession = null;
          await chrome.storage.local.remove('currentLearningSession');
          sendResponse({ ok: true });
          break;
        }
        case 'backend:error': {
          if (activeTabId != null) {
            try {
              await chrome.tabs.sendMessage(activeTabId, {
                type: 'overlay:error',
                message: msg.message
              });
            } catch (e) { /* ignore */ }
          }
          break;
        }
      }
    } catch (err) {
      console.error('[kami-subs bg]', err);
      sendResponse({ ok: false, error: String(err) });
    }
  })();
  return true; // keep channel open for async sendResponse
});

chrome.tabs.onRemoved.addListener(async (tabId) => {
  if (tabId === activeTabId) await stopCapture();
});
